### PR TITLE
Fixes #3: Format String With Named Arguments

### LINKED ISSUE #3: format string with unnamed arguments
Running `genpot` yields;

```
ps_watcher.py:286: warning: 'msgid' format string with unnamed arguments cannot be properly localized:
                            The translator cannot reorder the arguments.
                            Please consider using a format string with named arguments,
                            and a mapping instead of a tuple for the arguments.
```

### PR DESCRIPTION
**Pull request by pipix51**
This pull request solves #3. I added the named arguments to the format string in `ps_watcher.py`. 

- I then tested the `genpot` command and the command executed successfully. 
- I also tested other commands such as `dist_source` and `dist_xo` and they work fine. 
- I also ran the `install` command - there were no errors but the activity still does not work from #1

### CODE REVIEW

**Comment by walterbender** [comment]
(1) While I think your solution will work, it is not the typical way we handle these sorts of formatting issues with Sugar. More typical would be something along the lines of:

_('this is a string to be translated %(foo)s and %(bar)s') % {'foo': foo_value, 'bar': bar_value}

(2) Could you please run pep8 on the file and fix the formatting errors (yes--many are unrelated to your commit.)

**Comment by pipix51** [comment]
Sure thing, I'll be working on it.

**Comment by pipix51** [comment]
Apologies for the numerous commits, some PEP8 errors only pop up when others have been corrected. There still exists some errors that I cannot correct (such as `E501 line too long` ) as they would fragment the strings, however for most other errors they have been corrected.

**Comment by walterbender** [comment]
You could change:

+ _('Activity %(path)s emitted BuddyJoined("%(buddy)s") or mentioned the buddy in GetJoinedBuddies') %

to:

+ _('Activity %(path)s emitted BuddyJoined("%(buddy)s") \
or mentioned the buddy in GetJoinedBuddies') %

**Comment by pipix51** [comment]
All the PEP8 errors (especially E501 errors) have been resolved.

**Comment by walterbender** [comment]
These changes are great. I cannot run the activity on my version of Sugar because it relies on HippoCanvasBx, which is deprecated.

**Comment by quozl** [comment]
Won't test until #1 is fixed.

**Comment by quozl** [comment]
Given #9, closing this.

**Pull request closed without merging**
