### PR TITLE
Add license and repository metadata

### PR DESCRIPTION
**Pull request by shivamchadha**
Added a LICENSE file, and a repository field in myactivity.info.
This is a part of GCI task.

### CODE REVIEW

**Comment by shivamchadha** [comment]
@edsiper please take a look.

**Comment by quozl** [comment]
Review.  Won't merge, sorry.

- [x] please use COPYING for the file name, not LICENSE.txt,
- [x] please use GPLv2 text in COPYING, because that's what the license is in the activity.info and most of the python source files,
- [x] please also add the LGPLv2 text in a COPYING.LGPLv2 file, because this different license is used in some python source files,
- [x] please use the Sugar Labs repository in the activity.info file, not your own.

Also, please improve your commit messages, see [making commits](https://developer.sugarlabs.org/contributing.md.html#making%20commits).

**Comment by chimosky** [comment]
@shivamchadha the repo link is incorrect, it should be .eg. https://github.com/sugarlabs/activity.git.

**Comment by shivamchadha** [comment]
@chimosky Should it be activity.git or analyze.git?

**Comment by quozl** [comment]
Please don't use .txt on the end of the COPYING file names.

Look at the clone URL for the repository main page to see what format it is in.

Look at other activities that have a repository value in their activity.info file.

**Comment by quozl** [comment]
Thanks, much improved.

Next problem; the text in COPYING and COPYING.LGPLv2 is not the same text as the original licenses, in particular all the indentation and line wrapping has been lost.

GitHub and many downstream distributions use an md5sum or sha256sum of the COPYING file to quickly check the license; that won't work with your versions.

**Comment by shivamchadha** [comment]
@quozl  Please take a look.

**Comment by quozl** [comment]
Reviewed, will merge.

* COPYING is identical to http://www.gnu.org/licenses/gpl-2.0.txt
* COPYING.LGPLv2 is an edit of http://www.gnu.org/licenses/lgpl-2.1.txt with whitespace removed,
* repository is correct.

**Pull request merged**
